### PR TITLE
concatBytesToArray

### PR DESCRIPTION
**Pull request by TeknoCepni**
Created a function that returns byte array. Take paremeters of byte values, concat all of them and returns a single array.
Example:
byte array = new byte[2];
array = concatBytesToArray(0x06,0x01);

### CODE REVIEW

**Comment by TeknoCepni** [comment]
I signed it!

**Comment by Mihai238** [comment]
Hello,

Why not simply use `byte[] array = new byte[]{0x64, 0x61};` ?

**Comment by TeknoCepni** [comment]
Hello,
If you wanna add many byte values and you don't know how many. You can't this structure.
Thanks your comment.

**Comment by jonahgreenthal** [comment]
But you have to either know how many you have (to pass them into the function) or pass in an array to begin with. Calling this method creates the array anyway (that's how varargs works), and your method just copies it. I see no use for such a method.

**Comment by TeknoCepni** [comment]
If you want to concat many byte values. Its useful. 
Thanks your comment.

**Comment by kluever** [comment]
I agree with @TeknoCepni - I don't see why this method is useful. If you're passing var-args, then you might as well just use `new byte[] {a, b, c}`.

**Comment by TeknoCepni** [comment]
I am new here.@kluever  I used to merge this method for fetching mbus datas. But you are right. 	
This can also be done in such this way.
Thanks your comment.

**Pull request closed without merging**
