### PR TITLE
Add LCM method for BigIntegers

### PR DESCRIPTION
**Pull request by srinivascodes**
`/*Returns least common multiple of two BigIntegers using gcd method*/`

### CODE REVIEW

**Comment by perceptron8** [comment]
@srinivascodes I suspect this PR won't be merged anyway, so here's my two cents:

- Do not check for equality using `==`. Use `equals` instead. It's possible to construct `BigInteger` equal to `BigInteger.ZERO` but not being the same instance as `BigInteger.ZERO`. One of many possibilities is to call `new BigInteger(0, new byte[0])`.
- First divide, then multiply. It's more efficient. As rounding is indeed `UNNECESSARY`, don't use it at all (it is sufficient to use `BigInteger.divide`).
- There's no need to call `abs()` more than once.

```
public static BigInteger lcm(BigInteger a, BigInteger b) {
	if (a.equals(BigInteger.ZERO) || b.equals(BigInteger.ZERO)) {
		return BigInteger.ZERO;
	}
	BigInteger gcd = a.gcd(b);
	return a.divide(gcd).multiply(b).abs();
}
```

**Comment by srinivascodes** [comment]
@perceptron8 Thanks for your valuable advice. Changed my code's implementation. 
By the way, why do you suspect that this PR won't be merged? Is it because, there is no requirement of lcm method or is it like the implementation is not good enough?

**Comment by jbduncan** [comment]
@srinivascodes I can't speak for @perceptron8, but I suspect that from reading [this comment](https://github.com/google/guava/pull/3061#issuecomment-371537843) from one of the Guava team members, and also from what I personally know of the Guava team, that they will want to go through their rigorous internal API review process first, which will probably mean that you'd need to reimplement your efforts from scratch by the time they're ready to give feedback, if they haven't gone and implemented it themselves inside Google.

It's for that reason that they suggest in their contribution guidelines that [people who want new APIs should raise an issue first and that code should come afterwards](https://github.com/google/guava/blob/master/CONTRIBUTING.md#api-changes). :)

**Comment by jbduncan** [comment]
I hope that this sheds some light on things for you. ;)

**Comment by perceptron8** [comment]
@srinivascodes My intuition was based mostly on contribution guidelines that @jbduncan mentioned. BTW you may still like to include some tests.
> 1. Any significant changes should be accompanied by tests. The project already has good test coverage, so look at some of the existing tests if you're unsure how to go about it.

**Comment by cgdecker** [comment]
I'm going to close this for now; there's already an issue (#3060) open requesting that this be added and until we decide that it's something we want to do, having a PR with code for it doesn't help much. Writing the code is generally the easy part.

**Pull request closed without merging**
