### PR TITLE
Extensions for Preconditions API

### PR DESCRIPTION
**Pull request by jakubmalek**
1. Addition of callback support for Preconditions API :
- checkArgument(boolean expression, Supplier<Object> errorMessge)
- checkState(boolean expression, Supplier<Object> errorMessge)
- checkNotNull(T reference, Supplier<Object> errorMessge)
- check(boolean expression, Supplier<TException> exception)
1. Throwable.catchException utility along with ThrowableAction interface and ThrowableActions utility methods.

### CODE REVIEW

**Comment by jakubmalek** [comment]
I signed it!

**Comment by lukesandberg** [comment]
re: Preconditions

why not just pass a custom object with an overridden toString method?

**Comment by lowasser** [comment]
This makes some sense in Java 8 where a Supplier is just a lambda and an
Object with an overridden toString is an anonymous inner class.  And using
this approach at all lets you avoid front loading computations on the
objects that get captured by the lambda.

That said, until Java 8, the Object anonymous class is just as good.

**Comment by kevinb9n** [comment]
On Wed, May 25, 2016 at 10:13 AM, Louis Wasserman <notifications@github.com>
wrote:

This makes some sense in Java 8 where a Supplier is just a lambda and an
> Object with an overridden toString is an anonymous inner class. And using
> this approach at all lets you avoid front loading computations on the
> objects that get captured by the lambda.
>

Preconditions was never designed with the notion that "if you *ever* have
to revert to an if/throw something has gone terribly wrong".

When I see circuitous things like this being done, I feel (more) sad that
we ever introduced Preconditions at all.



> That said, until Java 8, the Object anonymous class is just as good.
>
> On Wed, May 25, 2016, 9:44 AM Luke Sandberg <notifications@github.com>
> wrote:
>
> > re: Preconditions
> >
> > why not just pass a custom object with an overridden toString method?
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/google/guava/pull/2480#issuecomment-221631532>
>
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/pull/2480#issuecomment-221640710>
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by cpovirk** [comment]
Bulk closing all pull requests that are listed as needing CLA signing. If you'd like us to look at your pull request, you'll need to sign the CLA and report back here.

If this is a false positive, I apologize. Please reopen the pull request, and we'll have a look.

**Pull request closed without merging**
