### PR TITLE
WIP +eventbus Add EventDispatchTask to help retrieve the original event.

### PR DESCRIPTION
**Pull request by hepin1989**
I need this to retrieve the original event

### CODE REVIEW

**Comment by hepin1989** [comment]
@googlebot I signed it!

**Comment by nglorioso** [comment]
Hi there! We're unlikely to add features to EventBus anymore. 

I note that the subscribers receive the event directly, so you may be able to log or deal with the event without having the executor that runs the event subscriber callback be aware of the event being called-back.

**Comment by hepin1989** [comment]
@nglorioso Are you sure? If I am using an AsyncEvent bus, and the executor is using abort policy, then how can the subscriber know?

**Comment by hepin1989** [comment]
@nglorioso Ping

**Pull request closed without merging**
