### PR TITLE
Fix RegularContiguousSet.intersection to handle singleton results.

### LINKED ISSUE #2196: ContiguousSet.intersection doesn't handle singleton results.
Let a < x < b:

- [x].intersection([x]) should return [x], returns [],
- [x].intersection([a..b]) should return [x], returns [],
- [a..b].intersection([x]) should return [x], returns [],
- [a..x].intersection([x..b]) should return [x], returns [].

I'll create a PR in a minute.

### PR DESCRIPTION
**Pull request by perceptron8**
Fixes #2196.

### CODE REVIEW

**Comment by perceptron8** [comment]
oraclejdk7 and openjdk7 builds fail with:

> The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).
> 
> The build has been terminated.

It doesn't seem to be related to this PR.

oraclejdk8 build completes with:
> Done. Your build exited with 0.

If there's something else I can do, let me know.

**Comment by cgdecker** [comment]
The current build failure is an issue with the latest GWT 2.8.0 snapshot, which I reported over here: https://github.com/gwtproject/gwt/issues/9206

**Comment by lowasser** [comment]
This fix LGTM once the test issues are resolved.

**Comment by perceptron8** [comment]
I saw that gwtproject/gwt#9206 seems to be resolved.

Could someone restart following builds, please?

- https://travis-ci.org/google/guava/builds/86643322
- https://travis-ci.org/google/guava/builds/86655829

I'd like to avoid pushing commits just to trigger rebuild.

**Comment by perceptron8** [comment]
The last commit is not related to intersection - I hope you will find it valuable, however. I found that some assertions were too weak.

@cgdecker Thanks for restarting builds!

**Pull request closed without merging**
