### PR TITLE
allow inheriting from SettableFuture and overriding cancel() method

### PR DESCRIPTION
**Pull request by kvr000**
I'd like to be able to implement custom ListenableFuture class where I could easily override cancel(boolean) method. The SettableFuture seems to be best fit but unfortunately it's declared final. Removing this restriction makes it much more reusable.

### CODE REVIEW

**Comment by cpovirk** [comment]
The class you're looking for is `AbstractFuture`. I will add some doc to `SettableFuture` to point there. (We currently have doc on `ListenableFuture`, so I may just add a pointer back there.)

Another thing we need to do is figure out our recommendations for extending `AbstractFuture`. Our hope is that users will rarely have to override `cancel()` (which doesn't always get invoked on cancellation, surprisingly enough: https://github.com/google/guava/issues/1958 https://github.com/google/guava/issues/1905). In many cases, all you need is to override `interruptTask()`. For cases in which that is not enough, we are probably going to expose a `done()` hook for users to override (https://github.com/google/guava/issues/2075).

I'll leave this request open until I at least add the doc.

**Comment by kvr000** [comment]
Thanks for mentioning `interruptTask()`, this is definitely better than overriding full `cancel()` method.

However, I still need both the `cancel()` and `set()` / `setException()` method. I actually think that this is pretty common use case for asynchronous tasks that are finished not by returning from method but after some notification is delivered (e.g. another `ListentableFuture`, completion callback etc.). In such case I need future for which it's possible to set the result and custom method for interrupting the task.

I believe that SettableFuture is best candidate here. Is there any drawback by making it non-final?

**Comment by cpovirk** [comment]
`cancel()`, `set()`, and `setException()` are all available on `AbstractFuture`, too. (I haven't formed a full picture of your requirements, but I'm confident that anything that can be done with `SettableFuture` can be done with `AbstractFuture`.)

But I guess I have been dodging the question :) A reason for `SettableFuture` to be final is that it gives us freedom to perform [optimizations](https://github.com/google/guava/blob/60fe0bb1bf3257779474af8fd80a59cb9a2f402a/guava/src/com/google/common/util/concurrent/AbstractFuture.java#L701). Well, OK, for that particular optimization, we need only `get()` to be `final`, not `cancel()`. But we want to leave ourselves the freedom to do additional optimizations in the future. In fact, this `get()`-based optimization is new for Guava 19, so if we had permitted overriding of arbitrary methods, we would have prevented ourselves from introducing it. We also have the freedom to make other changes besides optimizations. (I don't remember if this has been important for `SettableFuture` yet, but that's the general principle at work. And again, for people who do need to extend the type, we provide `AbstractFuture`, so we're just pushing users to take a slightly different approach.)

**Comment by kvr000** [comment]
Well, I see the point that with current design it can save some execution time in rather special situations though I can't judge how common they are in guava or the software based on this.

However, as you mentioned - this is mainly about optimizing `get()`, not `cancel()`... I think marking `get()` as final in `TrustedFuture` would make it safer, more readable and clear on purpose and on the other hand wouldn't affect extendability of `TrustedFuture` and as a result the inherited classes would take advantage of those performance optimizations as well :-)

Personally I agree it's not a big deal to inherit it from `AbstractFuture` in exactly the same way how `SettableFuture` is currently implemented. But I don't like I have to reinvent the wheel / duplicate the code. So maybe we can consider introducing another intermediate class `AbstractSettableFuture` and final `SettableFuture`. Although as described above it probably would hardly bring any value from the originally proposed approach.

Additionally, I'm considering implementing a `Future` class where in case of code is already running and cancellation is requested, `get()` and listener processing would be called after `set()`/`setException()` methods are called instead of immediately after invoking `cancel()`. Do you think it would be worth merging into guava or shall I skip the step for this? :-)

**Comment by cpovirk** [comment]
I've added some documentation to `SettableFuture`.

When you refer to "duplicating the code," are you talking about duplicating the overrides of `set` and `setException` that exist only to make them accessible? Often this ends up being unnecessary if you call the methods from within your `AbstractFuture` subclass.

To your `cancel()` request, I think you're describing a `Future` that diverges from the `Future` spec. [That spec](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Future.html#cancel-boolean-) requires that the `Future` be done when `cancel()` returns.

**Comment by kvr000** [comment]
Yes, I'm talking about duplicating `set` and `setException`. If I was able to inherit from `SettableFuture` it would save me few common lines of code. I need to call them externally as in this case it's basically used implementing integration pattern between 3rd-party framework and guava based code. I.e. (simplified version) `3rdparty.method().addListener(() -> { guavaFuture.set(3rdpartyFuture.get()); }`

For the `cancel()` request - I don't think it's somehow in conflict with specification. The specification only says that `isDone()` must return true and `isCancelled()` true as well but doesn't say when. And actually as the future is handled asynchronously by listener anyway it doesn't make any difference when you really "finish" the future.

**Comment by cpovirk** [comment]
If the need to redeclare `set` and `setException` is distasteful, you can put your `3rdparty.method().addListener` call inside your `AbstractFuture` subclass, probably declared inside your `MyThirdPartyUsingService` class. This might turn out to be the simplest place to define your subclass, anyway, to keep the `set` and `cancel` logic near one another.

RE: "subsequent calls to `isDone()` will always return true": I think that the natural reading of "always" is "at any time," not "after some arbitrary future time." Otherwise, all the statement would be saying is "Once the `Future` is done, it's always done," and that doesn't seem like something to document on `cancel()`.

**Comment by kvr000** [comment]
That would be even worse because I would lose reusability of such class. And secondly I understand the original purpose of `SettableFuture` as the creating code doesn't yet know who and how updates the future. Otherwise it could be rather called Forwarded which in this case is just the listener.

RE: "subsequent calls to isDone()will always return true": But it still does. The only difference is that listeners invocation is postponed until the task is finished (if it already runs). The state of future would be always CANCELLED since the completion of `cancel()`and all the affected methods would return proper value.

**Comment by cpovirk** [comment]
You seem to be suggesting that the `isDone` concept of "completed" ("Returns `true` if this task completed") has no connection to the concept of "completed" used elsewhere in the `Future` docs ("The result can only be retrieved using method `get` when the computation has completed").

Returning to `SettableFuture` and `final`: I regret that I haven't formed a clear enough picture of how `SettableFuture` would be used in your code to be more helpful. As far as the feature request goes, though, the Guava team is satisfied with `AbstractFuture` as a solution here.

**Comment by kvr000** [comment]
Never mind. I can either copy the setters or base the code on spring SettableListenableFuture which is more open in these terms.

Thanks anyway.

**Pull request closed without merging**
