### PR TITLE
Adding checkPositive MathPreconditions before using value of x

### PR DESCRIPTION
**Pull request by dpsingh016**
Adding checkPositive MathPreconditions before using value of x in ceilingPowerOfTwo and floorPowerOfTwo methods.

### CODE REVIEW

**Comment by dpsingh016** [comment]
Updated email address

**Comment by lowasser** [comment]
Not sure why you feel this is necessary?  log2, which these methods call immediately, already does this check.

**Comment by dpsingh016** [comment]
Presently we are tightly coupled with log2 method to enforce the method contract "@throws IllegalArgumentException if {@code x <= 0}"

I'm following fail fast concept at this place. If we know that for non positive values of x this method is going to fail we can fail it even before calling log2 method.

**Comment by lowasser** [comment]
There's no reason to check twice.  We have tests to make sure the exception gets thrown somewhere, and throwing the exception is part of log2's contract, which we can depend on.

**Comment by cpovirk** [comment]
Bulk closing all pull requests that are listed as needing CLA signing. If you'd like us to look at your pull request, you'll need to sign the CLA and report back here.

If this is a false positive, I apologize. Please reopen the pull request, and we'll have a look.

**Pull request closed without merging**
