### PR TITLE
A utility for single execution of  Runnable

### PR DESCRIPTION
**Pull request by tareqhs**
A funtionality similar to ``Suppliers.memoize()`` for Runnable

### CODE REVIEW

**Comment by tareqhs** [comment]
I signed it!

**Comment by jolkdarr** [comment]
Hi @tareqhs 

Thanks for the reply.
For this kind of synchronization, I prefer to use an AtomicBoolean or a single short integer (0/1) avoiding the use of an object as lock.

**Comment by tareqhs** [comment]
Hi @jolkdarr

This is a slightly different behavior. My intended behavior is that everyone depends on the outcome of the Runnable and waits for it to finish if it has not finished yet. The behavior you are describing is _triggering_ the task only once.  Maybe we should have a separate ``Runnables.triggerOnce(Runnable)`` for that?

**Comment by ben-manes** [comment]
This seems similar in spirit to `RunnableFuture` in j.u.c.

**Comment by netdpb** [comment]
What does this do that `java.util.concurrent.FutureTask` doesn't?

```
Runnable once = new FutureTask<>(runnable);
once.run(); // runs!
once.run(); // already ran; doesn't run!
```

**Pull request closed without merging**
