### PR TITLE
Add Tables.synchronizedTable()

### PR DESCRIPTION
**Pull request by mostlymagic**
https://github.com/google/guava/issues/2156
Implementation similar to other synchronized collections.
Copy unit test template from SynchronizedMapTest.
Make Synchronized.SynchronizedMap package protected (VisibleForTesting).

### CODE REVIEW

**Comment by lowasser** [comment]
@cpovirk, I'm a little confused about whether or not we need the GWT code in here; I don't see anything along those lines internally?

**Comment by cpovirk** [comment]
In some cases, it's necessary to update the GWT sources. This isn't one of them.

Thanks to https://github.com/google/guava/commit/63360f3f588a4a30d2d2e43ee6ec3f724d38b546, we are no putting these "unimportant" sources in Github. In fact, the specific source touched here was deleted in that CL.

Background: Our GWT setup in Guava was weird: Some of the GWT files were autogenerated from the "server" sources, and others were manually written. But the autogeneration happened internally before we push our code to Github, so it was tricky to tell which is which. Nowadays, we don't do the autogeneration, so I think that the only GWT code left is "important" GWT code (well, aside from the *_gwt.java test files).

**Comment by cpovirk** [comment]
@lowasser , aside from teh GWT question, did you end up reviewing this?

**Comment by lowasser** [comment]
I don't think I did.  You're welcome to, @cpovirk, or I can do it if you'd rather.

**Comment by cpovirk** [comment]
Be my guest, @lowasser :)

**Comment by mostlymagic** [comment]
Lost my previous fork.
Requested Changes implemented in https://github.com/google/guava/pull/2377

**Comment by user454322** [comment]
This doesn't seem to be in `com.google.guava:guava:jar:20.0`. Where can it be found?

**Comment by jbduncan** [comment]
It's not merged into Guava yet @user454322, see https://github.com/google/guava/pull/2377. :)

**Pull request closed without merging**
