### PR TITLE
Clarified HashMultimap javadoc about concurrency

### LINKED ISSUE #3682: MultiMap concurrency unclear Javadoc
From https://github.com/google/guava/issues/135#issuecomment-472966705

The [javadoc for HashMultimap](https://google.github.io/guava/releases/27.0-jre/api/docs/com/google/common/collect/HashMultimap.html)  states:  

> This class is not threadsafe when any concurrent operations update the multimap. Concurrent read operations will work correctly.

Does this mean that it is thread-safe if only one thread writes to the map (while any number of threads may read simultaniously) ? The javadoc for [other MultiMap implementations](https://google.github.io/guava/releases/27.0-jre/api/docs/com/google/common/collect/ArrayListMultimap.html) is the same and i think it should be clearer on that.

### PR DESCRIPTION
**Pull request by Saucistophe**
Fixes #3682

### CODE REVIEW

**Comment by cpovirk** [comment]
Mass-closing PRs without an accepted [CLA](https://cla.developers.google.com/about). You're welcome to reopen if you get the check to pass.

**Comment by Saucistophe** [comment]
@googlebot I fixed it.

**Comment by Saucistophe** [comment]
@cpovirk I'm sorry, I've tried everything I could, I'm at a dead end. I signed my CLA.
I initially commited with another address, for which I signed too.
Is there any way I can get more information about what's going wrong?

Thanks in advance!

**Comment by cpovirk** [comment]
https://github.com/google/guava/pull/5261.patch shows your email address as carpentier.ch@gmail.

If you add the ".com," I think the check will pass.

**Comment by Saucistophe** [comment]
@googlebot I fixed it.

**Comment by Saucistophe** [comment]
God I feel stupid. Thanks for your help, I fixed it and opened a new PR (https://github.com/google/guava/pull/5265)

**Pull request closed without merging**
