### PR TITLE
FileBackedOutputStream constructor should take temp file dir #2205

### PR DESCRIPTION
**Pull request by JoeHale**
Simple change - added a few new constructors and passed the tmpDir in.
This will allow multiple threads to use this class and write to different places while preserving the existing functionality.

### CODE REVIEW

**Comment by JoeHale** [comment]
I have read/signed the CLA. I am not sure why it wont let me put this pull request up

**Comment by jbduncan** [comment]
@JoeHale It may not be accepting your PR because the email address you use to log into GitHub is different from the email address you assigned to your local Git installation's `user.email` setting.

Try double-checking the email address you set for `user.email` (following these instructions to set it or reset it if needed: https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup), and then try running `git commit --amend` to hopefully correct your commit with the right email address and then `git push --force-with-lease` to push the corrected commit.

**Comment by netdpb** [comment]
`FileBackedOutputStream` uses `File.createTempFile(String, String)`, which should create a unique file every time.

Can you help me to understand what problem this PR solves?

**Comment by cpovirk** [comment]
Mass-closing PRs without an accepted [CLA](https://cla.developers.google.com/about). You're welcome to reopen if you get the check to pass. Alternatively, feel free to open a plain issue to describe the change you'd like to see made.

**Pull request closed without merging**
