### PR TITLE
Creates a mutable TreeSet instance containing the given elements sort…

### PR DESCRIPTION
**Pull request by manzhizhen**
Creates a mutable TreeSet instance containing the given elements sorted by their natural ordering.

### CODE REVIEW

**Comment by netdpb** [comment]
Hi @manzhizhen. Thanks for your PR. I can't review it until you sign the CLA (see [above](https://github.com/google/guava/pull/7533#issuecomment-2505712348)).

But I don't see a feature request for this. Why aren't `new TreeSet<>(elements)` or `new TreeSet<>(Arrays.asList(a, b, c))` sufficient?

**Comment by manzhizhen** [comment]
> Hi @manzhizhen. Thanks for your PR. I can't review it until you sign the CLA (see [above](https://github.com/google/guava/pull/7533#issuecomment-2505712348)).
> 
> But I don't see a feature request for this. Why aren't `new TreeSet<>(elements)` or `new TreeSet<>(Arrays.asList(a, b, c))` sufficient?

Adding this method is mainly to ensure a consistent user experience and align with the Sets#newHashSet(E... elements)
 method

**Comment by netdpb** [comment]
> Adding this method is mainly to ensure a consistent user experience and align with the Sets#newHashSet(E... elements) method

That method has the following note in its Javadoc: "This method is not actually very useful and will likely be deprecated in the future." I think it's probably not worth it to add a new to-be-deprecated not-very-useful method.

Thank you for the suggestion!

**Comment by manzhizhen** [comment]
> That method has the following note in its Javadoc: "This method is not actually very useful and will likely be deprecated in the future." I think it's probably not worth it to add a new to-be-deprecated not-very-useful method.

ok

**Pull request closed without merging**
