### PR TITLE
Test setValue(null) (both success and failure cases)

### PR DESCRIPTION
**Pull request by nikhilbarar**
Added tests:
- entry.setValue(null)

### CODE REVIEW

**Comment by cpovirk** [comment]
Can you suppress the new methods in https://github.com/google/guava/blob/c2f8967beb5a6feb9b104739d453dc116982a76a/guava-testlib/src/com/google/common/collect/testing/TestsForMapsInJavaUtil.java#L156 ?

I'm interested to see if that fixes all the failures.

**Comment by nikhilbarar** [comment]
Thanks. `setValue` method was already present in the suppress list of ConcurrentSkipListMap and ForwardingNavigableMap tests.

I've added the new methods as well at both the locations, which fixed all the failures.

**Comment by cpovirk** [comment]
Thanks very much. I've submitted this internally. It will be mirrored out within the next few days, with you listed as the author.

**Comment by nikhilbarar** [comment]
Thanks 👍 Happy to help

**Comment by WilliamCollishaw** [comment]
Looks like this PR can be closed, all changes are available in master. See #3191

**Pull request closed without merging**
