### PR TITLE
rename literal

### PR DESCRIPTION
**Pull request by mjaow**
refactor the literal 6 in LockFreeBitArray to LONG_ADDRESSABLE_BITS

### CODE REVIEW

**Comment by mjaow** [comment]
I signed it!

**Comment by mjaow** [comment]
I signed it!

**Comment by cpovirk** [comment]
Thanks. We've submitted this internally, and it will be mirrored out the next time we push changes.

**Comment by mjaow** [comment]
@cpovirk @ronshapiro 
seems the Moe Sync #3366 test failed

**Pull request closed without merging**
