### PR TITLE
Fix for Issue 2714: https://github.com/google/guava/issues/2714

### PR DESCRIPTION
**Pull request by petermalone**
ReverseConverter, ConverterComposition, & FunctionBasedConverter classes implement Serializable without transient/serialized member variables

### CODE REVIEW

**Comment by lowasser** [comment]
I'm not sure I follow what you're going for with this.  Transient variables aren't serialized; these fields appear to need to be serialized...?

**Comment by petermalone** [comment]
I signed the CLA.

lowasser - it's in response to this: http://cwe.mitre.org/data/definitions/594.html & squid:S1948

"Fields in a Serializable class must themselves be either Serializable or transient even if the class is never explicitly serialized or deserialized. That's because under load, most J2EE application frameworks flush objects to disk, and an allegedly Serializable object with non-transient, non-serializable data members could cause program crashes, and open the door to attackers."

**Comment by petermalone** [comment]
Contributor License Agreement (CLA),I signed it!

**Comment by lowasser** [comment]
That, too, seems working as intended to me.  The documented behavior is that the generated Converters are serializable if the original converter is serializable, which is accomplished with the status quo: if the underlying Converter is Serializable the serialization will work, otherwise you will get an exception when serialization is attempted.

Marking these fields transient will cause a NullPointerException if the object is serialized and deserialized, even if the original object was serializable.  (If our tests pass with your change, that probably reflects a problem with the tests?)

**Comment by lowasser** [comment]
Or, rather, to be specific: the converter, if serialized and deserialized while the fields are transient, will throw an NPE on an attempt to use them for conversions.

**Comment by petermalone** [comment]
Understood - if you're fine with this, let me close the pull request.  

Thanks so much for the speedy response.

**Pull request closed without merging**
