### PR TITLE
Cleanup threads for CacheBuilderTest and FuturesTest

### PR DESCRIPTION
**Pull request by aoli-al**
This PR addresses #7319. Cleanup threads for `CacheBuilderTest` and `FuturesTest`

### CODE REVIEW

**Comment by cpovirk** [comment]
(Thanks, I expect to be interested in merging this if you can get the CLA sorted out!)

**Comment by aoli-al** [comment]
Thanks! It seems that the CLA is cleared https://github.com/google/guava/pull/7320/checks?check_run_id=27685732789

**Comment by ben-manes** [comment]
fwiw, technically these should shutdown if the test fails. Typically a try-finally would be ideal, but if you want to avoid that then overriding `setUp` and `tearDown` could work by creating a `Closer` per test instance and registering the shutdown with that.

**Comment by aoli-al** [comment]
Will it be okay to make `service` a class field and then initialize it in each test.  `tearDown` should call `service.shutdown` if service is not null?

**Comment by cpovirk** [comment]
I think the most important thing is shutting down when the test succeeds so that there aren't threads hanging around during some later test run that someone tries to attach a debugger to. And I think we're inconsistent about whether we bother to try to shut down in case of failure.

Let me see whether the internal reviewer is concerned or not, hopefully tomorrow.

**Pull request closed without merging**
