### PR TITLE
update travis-ci for new container based infrastructure and maven cachin...

### PR DESCRIPTION
**Pull request by codylerum**
Looks like this shaves 9+ minutes in total off the build and about 3 per sub build

### CODE REVIEW

**Comment by codylerum** [comment]
I signed it!

**Comment by cpovirk** [comment]
@cgruber , is this something that we should do?

**Comment by cgdecker** [comment]
This seems reasonable to me.

**Comment by cgdecker** [comment]
Thanks! This change has been made in commit 01d5493fa96a16e4217dd5c3d2e953fca0e93a94.

**Comment by cgruber** [comment]
Yeah.  This is good. Thanks!

**Pull request closed without merging**
