### PR TITLE
Added test for CharMatcher.retainFrom() method (issue #6069)

### PR DESCRIPTION
**Pull request by rilmay**
Hello!

This PR adds test for method CharMatcher.retainFrom

### CODE REVIEW

**Comment by chaoren** [comment]
@rilmay please sign the CLA.

**Comment by rilmay** [comment]
Hello @chaoren , I have already signed the CLA.

**Comment by rilmay** [comment]
@chaoren , please tell me when you plan to close this request

**Comment by chaoren** [comment]
Sorry, I was just triaging the issue. We don't have any immediate plans.

**Pull request closed without merging**
