### PR TITLE
digitsOfNFactorial, getNumbersOfDigit  Methods are added

### PR DESCRIPTION
**Pull request by ozanonurtek**
#### public static int digitsOfNFactorial(int n)

//This method calculates digits number of number n's factorial without calculating 'n!'
//For example:for n=5--> 5!=120 --> returns 3
#### public static int getNumbersOfDigit(int n)

//This method calculates digits number of n
//For example:for n=4129--> returns 4

### CODE REVIEW

**Comment by ozanonurtek** [comment]
I signed it!

**Comment by ozanonurtek** [comment]
I signed it!

**Comment by netdpb** [comment]
What use cases do you see for these methods? How often do you expect people to need to calculate these?

**Comment by ozanonurtek** [comment]
It might be helpful for scientific use. @netdpb

**Comment by netdpb** [comment]
I'm sure that's the case, but I'm not certain that that's useful frequently enough among Guava's users. We tend not to add features unless we have good evidence that they'll be generally useful and frequently used. Otherwise we could add thousands of correct features that won't get used.

I'm going to close this PR for now. If you find data that suggests that these methods would be more widely used than it seems, please reopen it.

Thank you for this suggestion.

**Pull request closed without merging**
