### PR TITLE
Promote HostAndPort out of Beta.

### PR DESCRIPTION
**Pull request by swankjesse**
It's all grown up.

### CODE REVIEW

**Comment by cpovirk** [comment]
Evidently we have a competing internal class that we've been intending to reconcile this with. Possibly we should just admit that we'll never get around to it :(

**Comment by kashike** [comment]
Changed your mind?

**Comment by swankjesse** [comment]
Stopped holding my breath!

**Comment by mikehearn** [comment]
This is kind of annoying. It's a useful utility class but I can't use it without hitting various warnings, IDE highlightings etc.

If you'll never get around to it, why not apply this PR? The class is obviously stable and hasn't changed for many years. It confuses and dilutes the meaning of `@Beta` for it to be stuck in limbo like this.

**Comment by AParise1217** [comment]
@cpovirk  Has this competing internal class been reconciled with `HostAndPort` yet? It looks like this class has yet be change since this initial PR was opened.

**Pull request closed without merging**
