### PR TITLE
Fix deadlock if compute function throw a RuntimeException

### PR DESCRIPTION
**Pull request by imario42**
If the computeIfAbsent methods fails with a runtime exception, successive calls to computeIfAbsent lock due to a call to oldValue.waitForValue which never will receive a value then.

A test case to reproduce this behavior - the second computeIfAbsent will never return and your app is frozen.
The pull request restores the previous state of the cache on RuntimeException and the test will finish correctly.

`public class TestGuava extends TestCase
{
    private Cache<String, Boolean> cache = CacheBuilder.newBuilder()
            .maximumSize(10000)
            .expireAfterAccess(30, TimeUnit.SECONDS)
            .build();
    private Map<String, Boolean> cacheMap = cache.asMap();

    private final static Boolean TEST_BOOLEAN = new Boolean(true);
    public void testComputeException()
    {
        try
        {
            cacheMap.computeIfAbsent("a", key ->
            {
                throw new IllegalArgumentException();
            });

            fail();
        }
        catch (Exception e)
        {
            // expected
        }

        Boolean ret = cacheMap.computeIfAbsent("a", key -> {
            return TEST_BOOLEAN;
        });

        assertEquals(Boolean.TRUE, ret);
        assertSame(TEST_BOOLEAN, ret);

        ret = cacheMap.computeIfAbsent("a", key -> {
            return new Boolean(true); // should not create a new entry
        });

        assertEquals(Boolean.TRUE, ret);
        assertSame(TEST_BOOLEAN, ret);
    }
}`

### CODE REVIEW

**Comment by imario42** [comment]
I signed it!

**Comment by ben-manes** [comment]
This should rethrow Throwable in case of an Error.

**Comment by imario42** [comment]
@ben-manes : You mean instead of catching "just" the RuntimeException (which actually is rethrown) to catch a Throwable, right? Else, I don't know which "Error" you mean.

**Comment by ben-manes** [comment]
Yes, use Throwable. Otherwise a [java.lang.Error](https://docs.oracle.com/javase/8/docs/api/java/lang/Error.html) or sneakily thrown checked exception will not be handled.

**Comment by imario42** [comment]
Well, thanks to Java 8 that one was easy to fix. Done!

**Comment by imario42** [comment]
I'd like to ask if there is something else I can do that this fix gets merged?

**Comment by schlosna** [comment]
I would also like to see this fix merged and released soon as I've seen a couple separate projects hit deadlocks on cache `compute` and the fix for https://github.com/google/guava/issues/2743 did not fully handle the above mentioned failure cases.

Thanks!

**Comment by dawid-stosur** [comment]
We also experienced this issue on PROD so also would like to see it merged ASAP as we use caches extensively throughout the whole project.

**Comment by imario42** [comment]
Maybe have a look at https://github.com/ben-manes/caffeine which does not suffer from this bug?

**Comment by ben-manes** [comment]
I think this was fixed in https://github.com/google/guava/commit/821082833783f76a1b384924f904ecfd0281ae63 (25.1)

**Comment by netdpb** [comment]
Closing this PR as it looks like the bug was fixed.

**Pull request closed without merging**
