### PR TITLE
ImmediateEventBus that uses Dispatcher.IMMEDIATE

### PR DESCRIPTION
**Pull request by DavesMan**
New child of EventBus that uses immediate Dispatcher, which isn't used in any impl as of now.

### CODE REVIEW

**Comment by DavesMan** [comment]
I've just inspected the latest version of Guava and there is still no equivivalent of my ImmediateEventBus so immediate Dispatcher is still unused in master version of Guava.
I wonder why this hasn't been merged? I still have to use my fork. Noone else needs synchronous immediate bus?

**Comment by maxim5** [comment]
This is definitely useful for testing.

**Comment by Hc747** [comment]
Bump - any reason why this isn't included..?

**Comment by cpovirk** [comment]
We've moved to discourage EventBus entirely, as discussed in https://guava.dev/EventBus.

**Pull request closed without merging**
