### PR TITLE
(refactor) some opportunities to use diamond operator

### PR DESCRIPTION
**Pull request by desmorto**

### CODE REVIEW

**Comment by jbduncan** [comment]
Hmm, I wonder if Android even supports the diamond operator...

**Comment by JakeWharton** [comment]
Diamond is a compilation​ feature only. Has nothing to do with runtime.

**Comment by desmorto** [comment]
well, travis had a android test as well...

**Comment by jbduncan** [comment]
Yep, looks like it passes Travis (which indeed runs the Android tests), so I've no objections to this!

**Comment by cpovirk** [comment]
I think I found a couple cases that didn't compile with `-source 7 -target 7` (which we use so that the Android version is usable under Java 7, too), thanks to difference in the compiler's type inference under those flags. But the rest of the changes are in. Thanks.

**Pull request closed without merging**
