### PR TITLE
Use api instead of compile for Android

### PR DESCRIPTION
**Pull request by jereksel**

### CODE REVIEW

**Comment by JakeWharton** [comment]
The direct analogous is `api`. `implementation` is merely an optimization that should be opted into.

**Comment by jereksel** [comment]
I signed it!

**Comment by jbduncan** [comment]
@JakeWharton I thought it was the other way round? Isn't `implementation` the same as `compile`, with `api` being the optimisation? :/

**Comment by jbduncan** [comment]
@JakeWharton Wait, I'm challenging myself now. I realise that I'm not 100% clear on the difference between `api` and `implementation`, so never mind. :)

**Comment by JakeWharton** [comment]
No. Compile transitively exposes the dependency on the classpath of
downstream modules which is the same as api. Implementation hides the
dependency. Of course Gradle doesn't enforce or validate any of this so
it's a giant footgun unless you know what you're doing.

**Comment by jereksel** [comment]
`api` it is then.

**Comment by cpovirk** [comment]
(Found https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation to back up Jake.)

**Comment by cpovirk** [comment]
Hmm, so should we change the JRE one to `api`, as well? It sounds like `compile` may be deprecated.

**Comment by JakeWharton** [comment]
Android projects use neither. API and implementation are available for all
Android plugins for about a year now. The reason these PRs are sweeping the
web is that they now wan when you use compile.

**Comment by cpovirk** [comment]
Ah! Thanks.

**Comment by jbduncan** [comment]
Hmm. It sounds to me that `implementation` is the most sensible default, and `api` should be used only if the `java-library` plugin is imported _and_ the given project wants to expose Guava types to its users. Is my understanding correct @JakeWharton?

**Comment by JakeWharton** [comment]
Your understanding is correct because you understand the implications.
Anyone who needs to look at the README to figure out how to add Guava
beyond maybe just copy/pasting the coordinates will not have that
understanding.

**Comment by jbduncan** [comment]
@JakeWharton Cool! So you're suggesting `api` here because it's the most liberal option and most equivalent to the older `compile`, am I right?

**Comment by cpovirk** [comment]
(Even for people who don't expose Guava in their APIs, I'd be a little nervous about excluding transitive dependencies from the classpath, given problems with static analyzers and perhaps annotation processors discussed in #2824 and #2721. (There could also be problems if people use Guava annotations but don't consider that "exposing an API," but that seems less likely.) I suppose that those problems are relatively unlikely to affect people, though.)

**Comment by cpovirk** [comment]
Anyway, I do like the idea of suggesting the thing that is more likely to work (even if it's slower in some cases -- and I suspect only marginally so, since Guava isn't going to be changing between one build and the next). It is a little sad that this exports Guava to downstream targets, but that seems like the lesser evil (and no worse than what people see today).

One final thought: We _could_ decide to give instructions for each of...

- Java 8+
- Java 7
- Android

...where the Java 7 instructions look like the _current_ Android instructions and the Android instructions look like your new ones. But I'm not sure that's worth the potential confusion.

**Comment by jbduncan** [comment]
@cpovirk I think it's worth at least changing the remaining `compile` instruction for "guava-jre" to `api`, so that the Gradle installation instructions are consistent. :)

**Comment by cpovirk** [comment]
@jbduncan, @JakeWharton said above:

> I believe 'api' only exists for JRE projects if you're using the
> 'java-library' plugin. If you're using the regular 'java' plugin you only
> get 'compile' and 'implementation' (the idea being you're a leaf node and
> don't have anywhere to expose dependencies to).

So I worry that `api` won't exist for some people, and they'll be confused.

Does Gradle warn about `compile` in JRE projects like it does in Android projects?

**Pull request closed without merging**
