### PR TITLE
Some code can be simplified

### PR DESCRIPTION
**Pull request by Scott-YuYan**
1.Anonymous can be replaced with lambda.
2.`for` loop replaceable with `foreach`.

### CODE REVIEW

**Comment by JiangXi-YuYan** [comment]
@googlebot I signed it!

**Comment by netdpb** [comment]
We don't use lambdas in parts of Guava that also appear in Guava-Android, in order to minimize the diff between the two flavors. But we might accept the other changes, although we don't have a process that makes it simple to merge PRs.

**Comment by Scott-YuYan** [comment]
Ok,thanks for your letter and what can i do now？



---Original---

**Comment by liach** [comment]
Just revert the change in `AbstractBaseGraph`. The rest is very fine

**Comment by Scott-YuYan** [comment]
Ok,as you wish and i modified my commit.



---Original---

**Comment by liach** [comment]
uh no you did the wrong thing, you just reverted the changes google will accept

**Comment by Scott-YuYan** [comment]
Ok, I am done,very thankful.



---Original---

**Comment by amalloy** [comment]
Shoot, I tried to make @Scott-YuYan the commit author but I guess I didn't assign it correctly.

**Pull request closed without merging**
