### PR TITLE
add java lazy model

### PR DESCRIPTION
**Pull request by harbby**
scala lazy demo:
```
  private lazy val conn = DriverManager.getConnection("jdbc: full url....")
```
  java demo :
```
  public class LazyReferenceTest
{
    private final LazyReference<Connection> conn = LazyReference.goLazy(() -> {
        try {
            return DriverManager.getConnection("jdbc:url....");
        }
        catch (SQLException e) {
            throw new RuntimeException("Connection create fail", e);
        }
    });
   // .....
}
```

### CODE REVIEW

**Comment by jbduncan** [comment]
Hi @harbby, good news! Guava's [`Suppliers.memoize`](https://google.github.io/guava/releases/26.0-jre/api/docs/com/google/common/base/Suppliers.html#memoize-com.google.common.base.Supplier-) already does what this PR proposes, so `LazyReference` is not needed. :)

**Comment by harbby** [comment]
I signed it!

**Comment by harbby** [comment]
@jbduncan  Thank you, I will read Guava's Suppliers.memoize carefully.

**Comment by jbduncan** [comment]
@kashike Indeed! But I'd personally argue that, in the meantime, `Suppliers.memoize(javaSupplier::get)` is a relatively painless workaround. (Although I'm sure you already know of this workaround and would argue otherwise. 😉)

**Pull request closed without merging**
