### PR TITLE
Use defensive copying in `Immutable*Array.copyOf(*Stream)`

### PR DESCRIPTION
**Pull request by perceptron8**

### CODE REVIEW

**Comment by perceptron8** [comment]
This looks similar to #1855, so is this a design decision rather than an oversight?

**Comment by perceptron8** [comment]
There's one subtle difference. In case of `Collection.toArray`, "safety" is documented:
> The returned array will be "safe" in that no references to it are maintained by this collection.
(https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html#toArray--)

In case of `*Stream.toArray`, it is not.
> Returns an array containing the elements of this stream.
(https://docs.oracle.com/javase/8/docs/api/java/util/stream/DoubleStream.html#toArray--)
(https://docs.oracle.com/javase/8/docs/api/java/util/stream/IntStream.html#toArray--)
(https://docs.oracle.com/javase/8/docs/api/java/util/stream/LongStream.html#toArray--)

**Comment by cpovirk** [comment]
Interesting. My assumption would be that the `*Stream` methods are likewise intended to not maintain a reference. Maybe it's just not documented because a `Stream` that is being collected is not likely to have a preexisting backing array lying around the way that a `Correction` normally does, so there's less need to say "Don't do the natural but unsafe thing" explicitly?

**Comment by perceptron8** [comment]
Makes sense. I think that `toArray()` "safety" may be derived from terminal operation's definition (https://docs.oracle.com/javase/8/docs/api/java/util/stream/package-summary.html#StreamOps).

As you said almost 10 years ago:
> The problem of malicious implementations is one that we've intentionally decided not to tackle.
(https://github.com/google/guava/issues/1855#issuecomment-61355345)

In that case it's my oversight and this PR definitely shouldn't be merged, as it introduces unnecessary overhead.

Thanks for taking the time to look at this!

**Pull request closed without merging**
