### PR TITLE
Simplify some code

### PR DESCRIPTION
**Pull request by OLPMO**
Remove some redundant 'if' statement.Besides, I use .toArray(new MyClass[0])  replace .toArray(new MyClass[myList.size()]) for improving the  efficiency  of the code.
https://stackoverflow.com/questions/174093/toarraynew-myclass0-or-toarraynew-myclassmylist-size

### CODE REVIEW

**Comment by OLPMO** [comment]
@googlebot I signed it!

**Comment by OLPMO** [comment]
@googlebot I signed it!

**Comment by ljacqu** [comment]
-1 on the LocalCache changes, just as commented in PR #3492 this fixes what is presumably reported by an IDE at the expense of readability for no real reason.

**Comment by OLPMO** [comment]
@ljacqu oh,sorry. I prefer the version that I commit because I would do the same thing in my daily coding.I can also understand that different projects have different coding styles. Do you mean that all the changes of 'if' statement is unnecessary? If you think so, I would revert them into the master problem!

**Comment by OLPMO** [comment]
@ljacqu  I think that 'sum == 0' needs to be preserved because 'sum == 0' itself has the meaning of isEmpty. Positive thinking is more conducive to people's understanding than negative thinking.If you do not agree with that. I can also revert other 'if' statement to the master version.
Look forward to your reply.

**Comment by ljacqu** [comment]
Sorry if there was any misunderstanding, I‘m not in any way affiliated/involved with Guava – I just posted a comment as an individual passing by :)

**Comment by OLPMO** [comment]
@ljacqu  That’s all right.I am very glad that you can reply to this pr.Thanks for your suggestion

**Pull request closed without merging**
