### PR TITLE
Implement tryLockUninterruptibly

### PR DESCRIPTION
**Pull request by arhimondr**
Based on awaitUninterruptibly(Condition, ..)

### CODE REVIEW

**Comment by original-codematrix** [comment]
@arhimondr Before this can/will be merged you need to sign the cla. Check the message from the googlebot.

**Comment by arhimondr** [comment]
@original-codematrix I'm on it. Hopefully I'm going to be able to sign soon.

**Comment by arhimondr** [comment]
@googlebot I signed it!

**Comment by arhimondr** [comment]
@original-codematrix done

**Pull request closed without merging**
