### PR TITLE
Make AbstractFuture compatible with ForkJoinPool by catching exceptions from property retrieval

### PR DESCRIPTION
**Pull request by ElliottBrossard**
Context: https://github.com/google/guava/issues/3784

### CODE REVIEW

**Comment by ElliottBrossard** [comment]
I submitted the corporate CLA on behalf of Snowflake, but I need our authorized signer (our VP) to click through the agreement still. Once that happens, I'll trigger the cla/google check again.

**Comment by ElliottBrossard** [comment]
Hmm is there a way to see the test outputs for Travis CI? The log indicates that the new test fails, but I don't see that `/home/travis/build/google/guava/guava-tests/target/surefire-reports` is made available anywhere...

**Comment by cpovirk** [comment]
On [the job log page](https://travis-ci.org/google/guava/jobs/643496489), you can scroll _way_ to the bottom and click the `$ util/print_surefire_reports.sh` line and -- I see that it's not working :( I will have a look. Sorry about that.

**Comment by cpovirk** [comment]
Odd. It works for me locally (also maven-surefire-plugin:2.7.2, though only Maven 3.5). I wonder what's different about Travis.

If you're lucky, the problem will reproduce for you locally:
`mvn clean install "-Dtest.include=**/AbstractFutureInnocuousThreadTest.java"`

(You can probably skip the `clean` part, but I am always nervous about doing so.)

**Comment by cpovirk** [comment]
OK, I patched in your PR, so I have updates on 2 fronts:

First, the failure is this:

```
testAbstractFutureInitializationWithInnocuousThread_doesNotThrow(com.google.common.util.concurrent.AbstractFutureInnocuousThreadTest)  Time elapsed: 0.151 sec  <<< ERROR!
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "closeClassLoader")
  at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
  at java.security.AccessController.checkPermission(AccessController.java:884)
  at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
  at java.net.URLClassLoader.close(URLClassLoader.java:289)
  at com.google.common.util.concurrent.AbstractFutureInnocuousThreadTest.tearDown(AbstractFutureInnocuousThreadTest.java:80)
...
```

I am able to reproduce it locally -- but _not_ when using the `test.include` flag from my previous post. It's possible that this means that your test is affected by a previous test's incomplete cleanup or other poor hygiene (`AbstractFutureFallbackAtomicHelperTest`? `AbstractFutureCancellationCauseTest`?).

Second, I'm not completely sure what's up with `util/print_surefire_reports.sh`. Locally, I get a "successful" run but with no results with your commit patched in. That's because I'm seeing `.xml` files for most tests but _not_ seeing one for _your_ test. Maybe that's related to the `SecurityManager`?

I don't know why the situation would be different under Travis, under which there are apparently _no_ `.xml` files....

**Comment by cpovirk** [comment]
Now I am more confused!

In an attempt to narrow down which tests were causing the problem, I ran:
`mvn clean install "-Dtest.include=%regex[.*util.concurrent.*.class]"`

That got this far:
```
Running com.google.common.util.concurrent.AbstractExecutionThreadServiceTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.09 sec
Running com.google.common.util.concurrent.AbstractFutureCancellationCauseTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.042 sec
Running com.google.common.util.concurrent.AbstractFutureFallbackAtomicHelperTest
Tests run: 42, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 33.034 sec
Running com.google.common.util.concurrent.AbstractFutureInnocuousThreadTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.073 sec
```

Those all appear to be successes. But then the run aborted, claiming:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.7.2:test (default-test) on project guava-tests: There are test failures.
```

So I'm not sure what's up. Hopefully it will be clearer to you from the code.

**Comment by ElliottBrossard** [comment]
Thanks for taking a look! I wonder if resetting the `SecurityManager` to its original state at the end of the test would fix the problem...I'll give that a shot locally without the test filter and then see if it passes, then see if another Travis run will succeed.

**Comment by ElliottBrossard** [comment]
I really wish I could see the test output from Travis...I tried resetting the `SecurityManager` with `System.setSecurityManager(null);` at the end of the test, and both `mvn clean install "-Dtest.include=%regex[.*util.concurrent.*.class]"` and `mvn clean install "-Dtest.include=**/AbstractFutureInnocuousThreadTest.java"` pass for me now, but it looks like the tests through Travis are still failing based on the result above :(

Is `/home/travis/build/google/guava/guava-tests/target/surefire-reports` kept around in any logs/outputs?

**Comment by ElliottBrossard** [comment]
Let's check on the CLA status at least, since we submitted the corporate one:

@googlebot I signed it!

**Comment by ElliottBrossard** [comment]
@googlebot I signed it!

**Comment by ElliottBrossard** [comment]
Woohoo, the CLA check passes now.

Separately, though, I found a way to avoid depending on `ForkJoinPool` within Arrow Flight, so it's fine if `AbstractFuture` tries to access properties, and I'm not blocked on this PR any more. I'm happy to try to see it to completion, but it's not urgent in any case.

**Comment by cpovirk** [comment]
Thanks! I grabbed your test and tweaked it to use a custom `SecurityManager` subclass instead of writing a policy file. That appears to be enough to get `mvn clean install` to pass. Do you have any comments on the result, https://github.com/google/guava/pull/3795?

**Comment by cpovirk** [comment]
(You can ignore the second copy of the files (from the `android` directory). I probably should have omitted that copy from the PR.)

**Comment by ElliottBrossard** [comment]
Nice, LGTM! Thanks for figuring out a way to make it work. It sounds like this project doesn't merge changes from Github anyway, so we can close this PR if you want to proceed with submitting your version to google3 (and then I'm assuming the changes get exported to Github at some point).

**Comment by cpovirk** [comment]
Right, we'll make the equivalent change internally and then mirror it back out (with your name attached). That will automatically close this PR, so we can keep it open just in case I somehow forget about it :)

**Pull request closed without merging**
