### PR TITLE
Fixed double slicing ByteSource #3501

### LINKED ISSUE #3501: Slicing a ByteSource twice throws an unexpected IllegalArgumentException
Currently, trying to slice a `ByteSource` twice throws an unexpected `IllegalArgumentException` if the `ByteSource` returned after the first slice has a length smaller than the offset of the subsequent slice. For example, this code throws an `IllegalArgumentException`:

```
import com.google.common.io.ByteSource;

public class GuavaTest {
    public static void main(String[] args) {
        ByteSource.concat().slice(0, 3).slice(4, 3);
    }
}
```

That is against the documentation, where it is specified that it should return an empty `ByteSource`.

### PR DESCRIPTION
**Pull request by Buddy119**
Fixes #3501

add maxLength < 0 to check whether the offset is greater than the source size. If so, return an empty source according to the API description.

### CODE REVIEW

**Comment by Buddy119** [comment]
I signed it!

**Comment by Buddy119** [comment]
I signed it!

**Comment by Buddy119** [comment]
@googlebot  signed it!

**Comment by Buddy119** [comment]
@googlebot I signed it!

**Comment by Buddy119** [comment]
@googlebot I fixed it.

**Comment by Buddy119** [comment]
@googlebot I fixed it.

**Comment by Buddy119** [comment]
@googlebot I fixed it.

**Comment by Buddy119** [comment]
@googlebot I fixed it.

**Comment by Buddy119** [comment]
Can someone help me to see why the CLA check is still failed. I checked the CLA signment and do not find any mistake.

**Comment by Buddy119** [comment]
@googlebot  I fixed it.

**Comment by cpovirk** [comment]
Your Git commit uses an email address @outlook.com. It looks like you signed the CLA with your GMail address.

You can amend your commit (https://stackoverflow.com/a/3042512/28465) and force push it.

**Comment by Buddy119** [comment]
@cpovirk Done. Thanks a lot for your reply

**Comment by cpovirk** [comment]
Thank you. Two comments:

- Add the example code you gave as a test.
- It looks like your `Lists.partition` change ended up as part of this PR, too. I'll look at it in #3828, so see if you can back it out of this PR.

**Comment by Buddy119** [comment]
@cpovirk 
Hi, As I am new for  git and github, so I do not know how to amend this PR. So I submit a new PR and add test in the new PR. Please close this PR. The new PR is #3829. I am sorry for the inconvenience

**Comment by cpovirk** [comment]
Sounds good. Thanks!

**Pull request closed without merging**
