### PR TITLE
Applied skeletal implementation to interface migration automated refactoring

### PR DESCRIPTION
**Pull request by khatchad**
This is a semantics-preserving refactoring that migrates existing method implementations in classes to the corresponding implemented interface methods as `default` methods. The tool **does not** add new code; it only rearranges *existing* code.

We have upgraded the compilation process to use Java 8 so that default methods can be used. However, we realize that this may not be acceptable. Still, any feedback you can supply would be helpful.

- We are evaluating a research prototype automated refactoring Eclipse plug-in called [Migrate Skeletal Implementation to Interface](https://github.com/khatchad/Migrate-Skeletal-Implementation-to-Interface-Refactoring). We have applied the tool to your project in the hopes of receiving feedback.
- The approach is very conservative. That may mean that not all changes that can be made were made. Please feel free to continue the refactoring manually if you wish.
- We only migrated methods declared in abstract classes with the hopes of such methods being suitable default methods in corresponding interfaces.
- The source code should be semantically equivalent to the original.

Thank you for your help in this evaluation! Any feedback you can provide would be very helpful. In particular, we are interested if each of the proposed changes are helpful or not.

### CODE REVIEW

**Comment by khatchad** [comment]
I signed it!

**Comment by kluever** [comment]
Thanks Raffi, but we've been hard at work on a Guava for Java 8 branch which should be out later this year. That being said, I'm going to close this out.

FYI @lowasser - you might be interested in seeing what was proposed here.

**Comment by khatchad** [comment]
Thank you for the consideration, @kluever! We'll be on the look out for the Java 8 branch

**Comment by khatchad** [comment]
Hi @kluever and @lowasser. I am thinking of applying for a [Google Faculty Research Award](http://research.google.com/research-outreach.html#/research-outreach/faculty-engagement/faculty-research-awards), deadline September 30, 2016, and proposing something based on this research. I know it is a ways away, but I was wondering if you know anyone that would be interesting in sponsoring the application, as that is one of the available fields. I can send more information if desired. Thanks!

**Pull request closed without merging**
