### PR TITLE
Allow user-provided Ticker in RateLimiter

### PR DESCRIPTION
**Pull request by findepi**
Fixes https://github.com/google/guava/issues/3037. Fixes https://github.com/google/guava/issues/1774

As mentioned in https://github.com/google/guava/issues/3037#issuecomment-570493413, this is needed to remove `Thread.sleep` from unit tests of classes that internally use `RateLimiter` (eg https://github.com/prestosql/presto/blob/cb62e11aa72116c13bcac50ddcfb8e0f01bbb02a/presto-hive/src/test/java/io/prestosql/plugin/hive/util/TestThrottledAsyncQueue.java#L105).

### CODE REVIEW

**Comment by findepi** [comment]
I'd use advice how to deal with https://github.com/google/guava/blob/d08dd756cce43c3c27714e2d99286de7d08ff709/guava/src/com/google/common/util/concurrent/RateLimiter.java#L482

**Comment by findepi** [comment]
@netdpb can you suggest me the correct way to deal with https://github.com/google/guava/pull/3759#issuecomment-570513834?

**Comment by netdpb** [comment]
I'm not sure. That's what makes this task nontrivial.

**Comment by findepi** [comment]
@netdpb @kluever 
Got it. At the same time, it's also a good thing to have.
(not being able to unit test code _because_ it uses Guava is so lame)

I propose that we introduce a `SleepingTicker` interface, with two methods.

* One for getting current time (Ticker)
* and another for sleeping no longer than until current time becomes x
  * for system clock-based implementation this will be Thread.sleep or "sleep uninterruptibly" (as current code uses the latter)

We don't need to provide a fake implementation (just as FakeTicker is not part of Guava API).

**Comment by findepi** [comment]
I am closing this PR. However, if you decide you want to review my contribution (along what i proposed or otherwise), let me know.

**Pull request closed without merging**
