### PR TITLE
Range add different

### PR DESCRIPTION
**Pull request by cnsunnysen**
I added the different method in range for some calculations

### CODE REVIEW

**Comment by cnsunnysen** [comment]
@googlebot I signed it!

**Comment by perceptron8** [comment]
Computing difference between 2 ranges is already possible with [ImmutableRangeSet](https://guava.dev/ImmutableRangeSet):

```java
ImmutableRangeSet.of(a).difference(b);
```

... which returns `ImmutableRangeSet<C>`. If you really need `List<Range<C>>`, you can use:

```java
ImmutableRangeSet.of(a).difference(b).asRanges().asList();
```

**Comment by perceptron8** [comment]
@cnsunnysen You should also take a look at https://github.com/google/guava/blob/master/CONTRIBUTING.md.

**Comment by cnsunnysen** [comment]
wow [ImmutableRangeSet](https://guava.dev/ImmutableRangeSet)，Thank you.
And I will take a good look at that document.

**Pull request closed without merging**
