### PR TITLE
Add Maven Wrapper to our repo.

### PR DESCRIPTION
**Pull request by cpovirk**
For now, I'm adding the wrapper for Maven 3.8.2, which is the version
most of us at Google have handy at the moment. Arguably we should switch
to 3.9.0, since much the point of the wrapper is to make us not have to
worry about which version we have installed :)

### CODE REVIEW

**Comment by netdpb** [comment]
Curious: Why are we doing this as a standard PR rather than through Copybara?

**Comment by cpovirk** [comment]
There's some explanation in CL 509334407. We'll see if Nick buys it :)

**Comment by Marcono1234** [comment]
Is this obsolete now due to #6783?

**Comment by cpovirk** [comment]
Oh, yes, thanks.

**Pull request closed without merging**
