### PR TITLE
Guava - debeta and spring clean

### PR DESCRIPTION
**Pull request by ThomasKoreman**
First of all this is my first project on Guava so I just did the simple part, removing @beta's and some deprecated methods that should've been removed earlier.
If there is anything incorrect to this PR please reply and feel free to give some feedback.
The de-``@beta`` stuff will close several issues already: #3403, #3360, #3253, (#3362 is also part of ``3360``).

### CODE REVIEW

**Comment by ThomasKoreman** [comment]
I signed it

**Comment by ChristianCiach** [comment]
I am not a Google, but I can't see this PR being merged. You've reformatted the entire source code, so there is no way to tell what was actually changed. In general, pull requests should touch as little surrounding code as possible. 

Because of all this reformatting, the diff is useless. I cannot check if the removed deprecated methods are actually allowed to be removed. According to the guava philosophy, deprecated api will not be removed anymore unless it is marked as beta:

> APIs without @Beta will remain binary-compatible for the indefinite future. (Previously, we sometimes removed such APIs after a deprecation period. The last release to remove non-@Beta APIs was Guava 21.0.) Even @Deprecated APIs will remain (again, unless they are @Beta). We have no plans to start removing things again, but officially, we're leaving our options open in case of surprises (like, say, a serious security problem).

**Comment by ronshapiro** [comment]
Until we've reviewed each of these tickets, I think it's worth holding off on this PR. We'll also possibly make those changes one-by-one.

**Comment by cgdecker** [comment]
We will not be merging this. Aside from the unnecessary reformatting, removing `@Beta` from any API is something we need to make a decision on on a case-by-case basis (we should be prioritizing this higher than we have, but actually removing the annotation is the easy part). And `@Deprecated @Beta` APIs that we haven't removed yet mostly haven't been removed for internal reasons; we'll get to them.

**Pull request closed without merging**
