### PR TITLE
Add Duration and Supplier<Duration> overloads for Supplier#memoizeWithExpiration

### PR DESCRIPTION
**Pull request by mfboulos**
Directly addresses #3688 

I don't want to step on any toes since I saw that `long, TimeUnit` overloads are in the cards for several classes, but I also see the use in a `Duration` supplier, so I went and wrote this up real quick so we can at least have it in the works.

One thing I noticed while writing this is that `com.google.common.util.concurrent.Internal#toNanosSaturated` is package-scoped internal, but the only method in there is applicable to all legacy API's that require a `long, TimeUnit`, and there are several scattered in `base`, `cache`, and `collect` under `com.google.common`. It might be worth considering gauging the need for it to public-scoped, if at some point the human race figures out how to prolong life indefinitely.

Also first contribution here, hope all looks good :)

### CODE REVIEW

**Comment by mfboulos** [comment]
@googlebot I signed it!

**Comment by jbduncan** [comment]
Hi @mfboulos, welcome to Guava. :)

I think it's worth mentioning that it's unlikely this PR will be merged, because the Guava team prefer to do API reviews internally (which is apparently the hard part) and then write the code themselves to match whatever API they've agreed on.

See the [contribution guidelines](https://github.com/google/guava/blob/master/CONTRIBUTING.md) for more information.

**Comment by jbduncan** [comment]
That being said, I'm sure that this code would be a great start for @chriskilding's needs, who opened #3688, if you're happy for them to take the code as-is. :)

**Comment by kluever** [comment]
> It might be worth considering gauging the need for it to public-scoped

FWIW, we have a copy of this in our (still internal) `com.google.common.time` package, which we hope to get around to releasing at some point.

**Comment by mfboulos** [comment]
Understandable! My intuition was to put this PR in there just to have the code handy for you guys, but I understand there's more discussion behind it since it's essentially an extension to the existing API.

**Comment by cpovirk** [comment]
We added the `Duration` overload recently, including [under Android](https://guava.dev/releases/snapshot-android/api/docs/com/google/common/base/Suppliers.html#memoizeWithExpiration(com.google.common.base.Supplier,java.time.Duration)). I don't know that we'll end up adding a `Supplier<Duration>` overload at all, but we can come back to this PR if we someday resume the discussion on https://github.com/google/guava/issues/3688 and decide to go for it.

**Pull request closed without merging**
