### PR TITLE
Removed @Beta for toImmutableList and toImmutableMap

### PR DESCRIPTION
**Pull request by yuyumao**
https://github.com/google/guava/issues/3251

### CODE REVIEW

**Comment by yuyumao** [comment]
I signed it!

**Comment by zshamrock** [comment]
@yuyumao just to double check do you also consider to remove `@Beta` from other immutable collection classes, like 
- `ImmutableSet`,
- `ImmutableListMultimap`, 
- `ImmutableBiMap`, 
- `ImmutableSetMultimap`, 
- `ImmutableSortedMap`, 
- `ImmutableSortedSet`

Maybe there are others, but these are the ones I've found.

**Comment by yuyumao** [comment]
@zshamrock I've added all the classes you listed

**Comment by danielhultqvist** [comment]
@netdpb Any updates on this PR? Seems that the failing Travis build is probably unrelated. My team are hesitant of using the collectors as it warns about the usage in IDEA

**Comment by cpovirk** [comment]
https://github.com/google/guava/pull/3393

**Pull request closed without merging**
