### PR TITLE
Add generics with Maps. fromProperties().

### PR DESCRIPTION
**Pull request by purplest**
Add generics with Maps. fromProperties().

It can use like this:
```java
Map<Integer, Integer> maps = fromProperties(prop, (k)->Integer.valueOf(k), (v)->Integer.valueOf(v));
```
It's very useful when we use it to convert properties to a generics map.

And in other way, we can implement with BiFunction<T, U, R> to expand this method.

### CODE REVIEW

**Comment by akhil-am** [comment]
I signed it!

**Comment by lowasser** [comment]
Can you explain your use case in more detail?  Why you're using `Properties` in the first place, given that it seems pretty ancient and rarely used?  I'm also not sure this adds all that much value over e.g. `properties.entrySet().stream().collect(toImmutableMap(...))`.

**Comment by ronshapiro** [comment]
It also seems a bit odd to me to have full pojos encoded in a properties file.

**Comment by nglorioso** [comment]
Unfortunately, it looks like we're not going to be able to accept this change. It sounds like there are alternatives provided (either working with `properties.entrySet()` or the `ImmutableMap<String, String>` returned currently and interpreting the correct values).

**Pull request closed without merging**
