### PR TITLE
Use optimized for loop indexOf()

### PR DESCRIPTION
**Pull request by manu-p-1**
Added length locally to loop. Ultimately depends on compiler optimization.

### CODE REVIEW

**Comment by manu-p-1** [comment]
I can go ahead and write a benchmark (why not) and post the result here later on!

**Comment by JakeWharton** [comment]
If you're already going this far, why not compute the subtraction only once?

**Comment by manu-p-1** [comment]
You are right. I'm quite interested in seeing the results

**Comment by ljacqu** [comment]
Guess the results weren‘t good :joy:

**Comment by manu-p-1** [comment]
Super negligible performance diff

**Pull request closed without merging**
