### PR TITLE
Throwables#lazyStackTrace unsupported on IBM JDK 6

### PR DESCRIPTION
**Pull request by fdesu**
Fix addresses a problem occurred on IBM JDK 6. To ensure 
that we can call underlying method, Throwables#getSizeMethod, 
to get  stack size, first a smoke test  with dummy exception. 
Once method executed with success, it is safe to return it for 
further usage.

Issue: https://github.com/google/guava/issues/2887

### CODE REVIEW

**Comment by fdesu** [comment]
For the sake of clarification: there were two obvious ways:

- Guard `AbstractList#size` in `Throwables#jlaStackTrace` with `try-catch`
- Make a dry call of `JavaLangAccess` and if it success, then assume, that it is safe to call it

We can go with the first option, however, I think, that second seems more elegant.

**Comment by cpovirk** [comment]
The second sounds fine to me. I just submitted your change for internal review.

**Comment by cpovirk** [comment]
(Another reason to prefer your second option is that it makes sure `lazyStackTraceIsLazy` returns `false` in the case in which we aren't going to provide lazy access.)

**Comment by fdesu** [comment]
@cpovirk 
Exactly. I think it just ensures that API works fine, instead of make only one method out of two work as designed.
However, I don't have any idea, how to simulate/test it with a unit test (most probably there's no way even to do that, since it more likely to be a system/end-to-end one)

**Pull request closed without merging**
